step_ca_url: https://step-ca.local.iamrobertyoung.co.uk
step_ca_fingerprint: 2fa81c8c3c991096376f31bd69fb9503f809d5a1140dbebadb3a6e5941e1ebc8
service_cert_name: "{{ fqdn }}"
service_cert_file: "/etc/ssl/certs/{{ service_cert_name }}.crt"
service_key_file: "/etc/ssl/private/{{ service_cert_name }}.pem"
ansible_provisioner_password: password
ansible_provisioner_password_file: /root/.step/config/ansible_provisioner_password.txt
